**Case Study**

you are managing the electronics section of a store. You need to track the sales of **3 products**:Headphones,Smartwatches,and Speakers
over **4 days** (Monday to Thursday)
Row 0:Headphones
Row 1:Smartwatches
Row 2:Speakers


In [2]:
import numpy as np

In [3]:
a=np.array([1500,3000,5000])

In [4]:
b=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

In [5]:
print(a.ndim)
print(b.ndim)
print(a.shape)
print(b.shape)

1
2
(3,)
(3, 4)


In [6]:
c=(b+2)

In [7]:
c

array([[12, 17, 10, 14],
       [ 7,  9,  6,  8],
       [ 4,  5,  4,  6]])

In [46]:
d=np.dot(a,c)

In [10]:
d


array([59000, 77500, 53000, 75000])

In [11]:
e=np.sqrt(d)

In [13]:
e

array([242.89915603, 278.38821814, 230.21728866, 273.86127875])

Slicing and Indexing

In [26]:
print(b[0,:])

[10 15  8 12]


In [27]:
print(b[:,0])
print(b[:,1])

[10  5  2]
[15  7  3]


Q -access the sales of speakers on thursday and using slicing extarct 2*2 sub array representing the sales of headphones adn smartwatches on monday

In [29]:
print(b[0,3])
print(b[1:,0:2])

12
[[5 7]
 [2 3]]


Q- flatten 3X4 daily sales into 1d array of 12 element using .reshape().
Convert sales data into 2X6 matrix
use np.linspace to create array of 10 equal intervals between 0 and 100 represent discount percentage

In [30]:
print(b.reshape(1,12))
print(b.reshape(2,6))

[[10 15  8 12  5  7  4  6  2  3  2  4]]
[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]


In [32]:
print(np.linspace(0,100,10))

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [34]:
np.random.randint(0,20,size=(3,4))

array([[17,  1,  0,  0],
       [ 4,  4,  5,  9],
       [15,  4, 12, 10]], dtype=int32)

In [37]:
np.random.rand(5)

array([0.70747817, 0.3027666 , 0.85317808, 0.68002258, 0.57487193])

Use of np.sum() to find the sales

In [42]:
np.sum(b)

np.int64(78)

In [44]:
b.sum(axis=1)

array([45, 22, 11])

Axis in Numpy

In [3]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[5 7 9]
[ 6 15]


Where in Numpy

In [6]:
arr=np.array([10,-5,20,-15])
result=np.where(arr<0,0,arr)
result

array([10,  0, 20,  0])

In [7]:
arr=np.array([1,2,3,4,5])

In [13]:
result=np.where(arr%2!=0,-1,arr)
print(result)

[-1  2 -1  4 -1]


In [9]:
marks=np.array([45,78,32,90,55])

In [12]:
status=np.where(marks>=50,"Pass","Fail")
print(status)

['Fail' 'Pass' 'Fail' 'Pass' 'Pass']


In [14]:
data=np.array([10,20,30,40,50])
mean_val=np.mean(data)
result=np.where(data>mean_val,mean_val,data)
print(result)

[10. 20. 30. 30. 30.]


Applying Where Condition in 2D Array

In [17]:
mat=np.array([
    [10,60,30],
    [80,20,90]])
result=np.where(mat>=50,1,0)
print(result)

[[0 1 0]
 [1 0 1]]
