In [3]:
import numpy as np

In [4]:
marks=np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])

In [5]:
print(marks.shape)
print(marks.dtype)
print(marks.size)

(5, 3)
int64
15


In [6]:
print(marks[1,:])

[45 60 55]


In [7]:
print(marks[:,2])

[90 55 95 35 75]


In [8]:
print(marks[0,1])

85


## task B

In [9]:
avg_marks=np.mean(marks,axis=1)
print(avg_marks)

[84.33333333 53.33333333 91.66666667 35.         70.        ]


In [10]:
avg_marks1 = np.mean(marks, axis=0)
print(avg_marks1)

[61.2 69.4 70. ]


In [11]:
check=np.where(avg_marks>=80,avg_marks,0)
print(check)

[84.33333333  0.         91.66666667  0.          0.        ]


In [12]:
new=(marks+5)
print(new)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


## Task C


In [13]:
check=np.where(marks>=50,1,0)
print(check)

[[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]


In [16]:
new=np.where(marks<40,0,marks)

In [19]:
print(new)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [65 70 75]]


## Task D

In [38]:
new_marks=np.where(avg_marks>=80,'Grade A',np.where(avg_marks>=70,'Grade B',np.where(avg_marks>=50,'Grade C',np.where(avg_marks<50,'No Grade',''))))

In [39]:
print(new_marks)

['Grade A' 'Grade C' 'Grade A' 'No Grade' 'Grade B']


# task E


In [40]:
new1=marks.copy()


In [47]:
new1[0,0]=0

In [ ]:
print(new1)
print(marks)

[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[75 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
