In [1]:
import numpy as np


In [8]:
arr = np.array([])


In [9]:
print(arr)


[]


In [10]:
type(arr)

numpy.ndarray

In [11]:
arr1=np.array([2,3,4,5,6,7,8,9])
print(arr1)

[2 3 4 5 6 7 8 9]


In [15]:
arr2=[10,12,13,14,15]

arr2=np.array(arr2)

print(arr2)
print(type(arr2))

[10 12 13 14 15]
<class 'numpy.ndarray'>


Array Properties

In [18]:
array=np.array([1,2,3,4,5])

In [19]:
print("Dimension ",array.ndim)
print("Number of elements",array.size)
print("Data type",array.dtype)

Dimension  1
Number of elements 5
Data type int64


In [21]:
var=[1,"Sam",9.5,True]

var=np.array(var)

print(var)
print(type(var))

['1' 'Sam' '9.5' 'True']
<class 'numpy.ndarray'>


In [23]:
string=["Hi","hello"]

string=np.array(string)

print(string)
print(type(string))

['Hi' 'hello']
<class 'numpy.ndarray'>


2-D Array

In [30]:
array2d=np.array([[],[],[]])

array_2d=np.array([[1,2],[3,4],[5,6]])

print(array_2d)
print("Dimension ",array_2d.ndim)
print(type(array_2d))

[[1 2]
 [3 4]
 [5 6]]
Dimension  2
<class 'numpy.ndarray'>


In [5]:
mat=np.array([[1,2,3],[4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

3D Array

In [31]:
array_3d=np.array([[[1,2],[3,4],[5,6]]])

print(array_3d)
print("Dimension ",array_3d.ndim)
print(type(array_3d))

[[[1 2]
  [3 4]
  [5 6]]]
Dimension  3
<class 'numpy.ndarray'>


Range of Numbers

In [ ]:
np.arange(101,502)


In [13]:
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

Printing Ones

In [21]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Printing Zeros in matrix form

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Printing Identity Matrix

In [22]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

Evenly Spaced Numbers

In [10]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

Random Module

Finding random values

In [45]:
np.random.randint(1,200,10)

array([ 61, 150, 177, 146,   7,   9,  90, 192, 178,  94], dtype=int32)

In [ ]:
##Random Number in Matrics
np.random.randint(1,200,size=(3,4))

array([[119, 147,  16,  14],
       [ 72, 193, 190,  43],
       [ 65,  36, 199,  97]], dtype=int32)

Finding Random Number of float type

In [47]:
np.random.randn(11)

array([ 1.20564274,  0.16653468,  0.14678359, -0.4637432 , -1.42908936,
       -2.25080922, -0.76973249,  1.51773789, -0.00892892,  0.61797263,
        1.13726721])

Finding 10 Random Number and Max Digit

In [50]:
a=np.random.randint(1,1000,10)
print(a)
print("Max:",a.max())

[362 489 494 714 301 690  12 701 951 409]
Max: 951


Finding Max Digit Index

In [51]:
np.argmax(a)

np.int64(8)

Finding Min Digit Index

In [52]:
np.argmin(a)

np.int64(6)

Finding Min value

In [53]:
a.min()

np.int32(12)

Type Conversion

In [11]:
arr=np.array([1.2,3.4,5.6])
arr_int=arr.astype(int)
arr_int

array([1, 3, 5])

Indexing and Slicing

In [13]:
arr =np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

10
50


1D Slicing

In [14]:
print(arr[1:3])
print(arr[:2])
print(arr[::2])

[20 30]
[10 20]
[10 30 50]


2D Indexing

In [18]:
mat=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(mat[0,1])
print(mat[1,2])

2
6


In [19]:
print(mat[:,1])  #2nd column

[2 5 8]


In [23]:
a=np.array([1,2,3])
b=a.copy()
b[0]=99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [24]:
a=np.array([1,2,3])
b=a #this will overwrite both the row a and b to point to same array so any changes made in b will reflect in a also
b[0]=99
print(a)

[99  2  3]


Basic Array Operations (VECTOR POWER)

In [2]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [3]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Scalar Operations

In [5]:
print(a+10)
print(a*4)

[11 12 13]
[ 4  8 12]


Unfus (universal function)

In [9]:
arr=np.array([1,4,9,16,25])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

[1. 2. 3. 4. 5.]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
25
1
11.0
55
8.648699324175862


Boolean Indexing

In [10]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [11]:
print(arr>25)

[False False  True  True  True]


Broadcasting Rule

In [12]:
arr=np.array([1,2,3,4])
print(arr+10)

[11 12 13 14]


In [14]:
mat=np.array([[1,2,3],
              [4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


In [15]:
row=np.array([1,2,3])
print(mat+row)

[[2 4 6]
 [5 7 9]]


Matrix Multiplication

In [16]:
A=np.array([[1,2],
            [3,4]])
B=np.array([[5,6],  #This is using Dot product
            [7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [17]:
print(A.T)

[[1 3]
 [2 4]]


Reshaping Arrays

In [27]:
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
