# Case Study 
**A university monitors electricity usage (in units) of 4 hostels over 7 days(Mon-Sun)**
##
**Array-Name:Electricity**
##
**Shape(4,7)**
##
**Rows:Hostels(H1,H2,H3,H4)**
##
**Cols:Days(Mon-Sun)**

In [1]:
import numpy as np

# Task A1

In [2]:
arr=np.random.randint(120,650,(4,7))

In [3]:
print(arr)

[[193 527 507 404 423 379 221]
 [297 314 124 370 247 309 403]
 [509 515 556 576 470 630 509]
 [127 537 193 579 319 417 375]]


# Task A2

In [4]:
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(4, 7)
2
28
int32


# Task B1

In [5]:
avg_usage=np.mean(arr,axis=1)
max_usage=np.max(arr,axis=1)
highest_avg=np.max(avg_usage)

In [6]:
print(avg_usage)
print(max_usage)
print(highest_avg)

[379.14285714 294.85714286 537.85714286 363.85714286]
[527 403 630 579]
537.8571428571429


# Task B2

In [7]:
total_consumption=np.sum(arr,axis=0)
highest_total=np.max(total_consumption)

In [8]:
print(total_consumption)
print(highest_total)

[1126 1893 1380 1929 1459 1735 1508]
1929


## Task C

In [9]:
penalized_usage=np.where(arr>550,arr*1.20,arr)
print(penalized_usage)

[[193.  527.  507.  404.  423.  379.  221. ]
 [297.  314.  124.  370.  247.  309.  403. ]
 [509.  515.  667.2 691.2 470.  756.  509. ]
 [127.  537.  193.  694.8 319.  417.  375. ]]


## Task D1

In [16]:
compare=np.where(avg_usage.reshape(4,1)>arr,True,False)
print(compare)

[[ True False False False False  True  True]
 [False False  True False  True False False]
 [ True  True False False  True False  True]
 [ True False  True False  True False False]]


## Task E1

In [11]:
new=np.reshape(arr,(1,28))
print(new)

[[193 527 507 404 423 379 221 297 314 124 370 247 309 403 509 515 556 576
  470 630 509 127 537 193 579 319 417 375]]


## Task E2

In [12]:
new1=np.reshape(arr,(2,14))
print(new1)

[[193 527 507 404 423 379 221 297 314 124 370 247 309 403]
 [509 515 556 576 470 630 509 127 537 193 579 319 417 375]]


## Task F1

In [13]:
ref_backup=arr
safe_backup=arr.copy()


In [14]:
arr[0,0]=0

In [15]:
print(arr)
print(ref_backup)
print(safe_backup)

[[  0 527 507 404 423 379 221]
 [297 314 124 370 247 309 403]
 [509 515 556 576 470 630 509]
 [127 537 193 579 319 417 375]]
[[  0 527 507 404 423 379 221]
 [297 314 124 370 247 309 403]
 [509 515 556 576 470 630 509]
 [127 537 193 579 319 417 375]]
[[193 527 507 404 423 379 221]
 [297 314 124 370 247 309 403]
 [509 515 556 576 470 630 509]
 [127 537 193 579 319 417 375]]
