# Case Study 
**A university monitors electricity usage (in units) of 4 hostels over 7 days(Mon-Sun)**
##
**Array-Name:Electricity**
##
**Shape(4,7)**
##
**Rows:Hostels(H1,H2,H3,H4)**
##
**Cols:Days(Mon-Sun)**

In [1]:
import numpy as np

# Task A1

In [2]:
arr=np.random.randint(120,650,(4,7))

In [29]:
print(arr)

[[460 255 312 602 546 197 623]
 [460 546 321 208 414 483 635]
 [317 439 133 534 269 215 285]
 [169 215 490 491 639 334 334]]


# Task A2

In [30]:
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(4, 7)
2
28
int32


# Task B1

In [31]:
avg_usage=np.mean(arr,axis=1)
max_usage=np.max(arr,axis=1)
highest_avg=np.max(avg_usage)

In [32]:
print(avg_usage)
print(max_usage)
print(highest_avg)

[427.85714286 438.14285714 313.14285714 381.71428571]
[623 635 534 639]
438.14285714285717


# Task B2

In [33]:
total_consumption=np.sum(arr,axis=0)
highest_total=np.max(total_consumption)

In [34]:
print(total_consumption)
print(highest_total)

[1406 1455 1256 1835 1868 1229 1877]
1877


## Task C

In [35]:
penalized_usage=np.where(arr>550,arr*1.20,arr)
print(penalized_usage)

[[460.  255.  312.  722.4 546.  197.  747.6]
 [460.  546.  321.  208.  414.  483.  762. ]
 [317.  439.  133.  534.  269.  215.  285. ]
 [169.  215.  490.  491.  766.8 334.  334. ]]


## Task D1

In [36]:
compare=np.where(avg_usage>arr,True,False)

ValueError: operands could not be broadcast together with shapes (4,) (4,7) 

## Task E1

In [37]:
new=np.reshape(arr,(1,28))
print(new)

[[460 255 312 602 546 197 623 460 546 321 208 414 483 635 317 439 133 534
  269 215 285 169 215 490 491 639 334 334]]


## Task E2

In [38]:
new1=np.reshape(arr,(2,14))
print(new1)

[[460 255 312 602 546 197 623 460 546 321 208 414 483 635]
 [317 439 133 534 269 215 285 169 215 490 491 639 334 334]]


## Task F1

In [40]:
ref_backup=arr
safe_backup=arr.copy()


In [41]:
arr[0,0]=0

In [42]:
print(arr)
print(ref_backup)
print(safe_backup)

[[  0 255 312 602 546 197 623]
 [460 546 321 208 414 483 635]
 [317 439 133 534 269 215 285]
 [169 215 490 491 639 334 334]]
[[  0 255 312 602 546 197 623]
 [460 546 321 208 414 483 635]
 [317 439 133 534 269 215 285]
 [169 215 490 491 639 334 334]]
[[460 255 312 602 546 197 623]
 [460 546 321 208 414 483 635]
 [317 439 133 534 269 215 285]
 [169 215 490 491 639 334 334]]
